name: CI Pipeline

on:
    push:
        branches:
            [ci/setup-ci-pipeline]
    pull_request:
        branches:
            [develop]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set Up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13' 
            
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Lint Dockerfile with hadolint
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: Dockerfile

            - name: Run test
              run : |
                  pytest

            - name: Build Docker Image
              run: docker build -t sensor-data:ci-test .

            - name: Run Image
              run: docker run -d -p 5000:5000 --name sensor-data sensor-data:ci-test 

            - name: Wait for app to start
              run: sleep 5

            - name: Call /temperature endpoint
              run: |
                curl --fail http://localhost:5000/temperature || exit 1
            


        
                       

