name: CI Pipeline

on:
    push:
        branches:
            [ci/setup-ci-pipeline]
    pull_request:
        branches:
            [develop]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set Up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13' 
            
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run test
              run : |
                  pytest
                       

