name: CI Pipeline

on:
  push:
    branches:
      - main           
      - develop        
      - 'feature/**'   
      - 'ci/**'        
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt

      - run: set e
      - run: pytest

  build:
    name: Build & Validate Docker Image
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t sensor-data:ci-test .

      - run: docker run -d -p 5000:5000 --name sensor-data sensor-data:ci-test
      - run: sleep 5

      - run: set -e 
      - run: curl --fail http://localhost:5000/temperature || exit 1
     
      - run: docker stop sensor-data
      - run: docker rm sensor-data

  